package constants

var WRONG_CREDENTIALS = "Please check if username and password is provided correctly"
var TOKEN_GENERATE_FAIL = "Failed to generate JWT token"
var INVALID_TOKEN = "Authorization token is not valid and SessionId cannot be extracted"
var USER_SESSION_FAILED_CREATE = "Failed to create session for User:"
var MISSING_AUTH_TOKEN = "Authorization Token is missing in the request"
var PARSE_TOKEN_FAIL = "Failed to parse authentication token"
var INVALID_SESSION = "Provided user session is invalid"
var REQUEST_ID_GENERATION_FAILED = "Failed to generate request id"
var TOKEN_SIGNING_FAILED = "Failed to sign the token"

const WARNING = "warning"
const UNDEFINED = "undefined"
const PASSED = "passed"
const FAILED = "failed"
const RUNNING = "running"
const CANCELLED = "cancelled"

var FAILED_BEGIN_TRANSACTION = "Failed to start a database transaction"
var FAILED_TO_GET_OBJ = "Failed to get %s from database"
var FAILED_TO_GET_BY_ID = "Failed to get %s By ID"
var FAILED_TO_DELETE_OBJ = "Failed to delete Object %s"
var FAILED_TO_CREATE_OBJ = "Failed to create Object %s"
var FAILED_TO_UPDATE_OBJ = "Failed to update Object %s"
var ITEM_NOT_FOUND = "%s item not found"
var COMMIT_FAILED = "Failed to commit the database transaction"
var FAILED_EXEC = "Failed to execute query"
var FAILED_TOTAL_ROWS = "Failed to count total rows"
var FAILED_SCAN = "Failed to scan results"
var ERRO_PROCESSING_FAIL = "Error processing %s"
var NO_ROWS_AFFECTED = "No rows affected for %s"

var POST_READ_ERROR = "Not able to read POST Body"
var INVALID_ID = "Invalid ID"
var INVALID_EMAILID = "Provided Email address is invalid"
var INVALID_PASSWORD = "Invalid password"

var EMPTY_FIELD = "Invalid Field %s provided, please check the content is not empty"
var UNAUTHORIZED = "Unauthorized to make this request"
