// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"starter/internal/app/controllers"
	"starter/internal/app/repository"
	"starter/internal/app/services"
	"starter/internal/config"
)

import (
	_ "starter/docs"
)

// Injectors from wire.go:

func InitializeApplication() *Application {
	dbPool := config.ConnectDB()
	crudRepository := Repository.NewCRUDRepository(dbPool)
	userRepository := Repository.NewUserRepository(crudRepository)
	restCaller := services.NewDefaultRestCaller()
	userService := services.NewUserService(userRepository)
	internalController := controllers.NewInternalController(dbPool, userService)
	userController := controllers.NewUserController(userService)
	mainRouter := NewRouter(dbPool, internalController, userController)
	application := NewApplication(dbPool, crudRepository, userRepository, restCaller, mainRouter, userController)
	return application
}
